### ISSUE TITLE
When installing express-kerberos it installs simple-kerberos which installs the wrong version of kerberos

### ISSUE THREAD

**Issue by shayfisher** [noamokman/simple-kerberos#5]
npm i express-kerberos fetches eventually version 0.0.24 of the package kerberos even the package.json of simple-kerberos was updated to version 1.1.3 
https://github.com/noamokman/simple-kerberos/blob/6f2a5ab53380f0ff2e9952d57cd032aef3f973f2/package.json#L57

**Comment by noamokman** [comment]
Hey, I just published the new version to npm 😄
